### ISSUE TITLE
How to restore a mysql DB?

### ISSUE THREAD

**Issue by aegershman** [andreasf/cf-mysql-plugin#13]
The README makes a comment about how this plugin can be used to dump and restore databases, however it does not appear to offer guidance on how to _restore_ a DB using the plugin.

Is it possible to use this plugin to restore a mysql db? e.g., given a mysql dump, could this plugin be used to upload/restore it to a mysql service?

**Comment by andreasf** [comment]
The plugin tries to be transparent in the sense that you should be able to run `cf mysql` anywhere where `mysql` works: all parameters and streams are passed on to the mysql client subprocess.

The typical way to load a dump generated with `mysqldump` is `cat dump.sql | mysql db-name`. With the plugin, you just replace "mysql" with "cf mysql" and use the service name: `cat dump.sql | cf mysql service-name`.

It's not what I would recommend for production purposes though, because it requires the local network connection to stay up and the SSH tunneling probably reduces throughput as well.

**Comment by aegershman** [comment]
Thank you @andreasf I appreciate it
